import { PDFParse } from "pdf-parse";

/**
 * B6: raw PDF bytes -> plain text. Both waste report types (Completo/Incompleto) are
 * generated by the same reporting tool, so this one function serves both parsers.
 * `pdf-parse`'s text extraction wraps multi-word table cells across lines (e.g. "Perda
 * Operacional" comes back as "Perda\nOperacional") — the row parsers are written with
 * that in mind, not against a cleaner layout.
 */
export async function extractPdfText(pdfBuffer: Buffer): Promise<string> {
  const parser = new PDFParse({ data: pdfBuffer });
  try {
    const result = await parser.getText();
    return result.text;
  } finally {
    await parser.destroy();
  }
}
